### ISSUE TITLE
Add shortcuts for using clipboard.

### ISSUE THREAD

**Issue by DieKautz** [hpi-swa-teaching/SketchMorph2#105]
As a user, I want to copy/cut/paste my selection with the usual shortcuts (ctrl+c, ctrl+x, ctrl+v), to use less clicks for doing the action.

**Comment by MariusDoe** [comment]
I think https://github.com/hpi-swa-teaching/SketchMorph2/issues/103#issuecomment-1118955997 applies here as well.

**Comment by RogerAK** [comment]
### Todo
Fix the bug, where you have to move the cursor outside the canvas, so that the selected shape is showed with the cursor.
