### ISSUE TITLE
Add layer system

### ISSUE THREAD

**Issue by MariusDoe** [hpi-swa-teaching/SketchMorph2#107]
As a user, I want to create multiple composable, stacked layers in order to work on different parts of my painting independently.

**Comment by RogerAK** [comment]
- [x] Click the eye to show and Hide (@DieKautz @RogerAK) (4)
- [x] Rename as an extra button (@DieKautz @RogerAK) (1)
- [x] Fix eraser size when switching layers (@DieKautz @Encotric) (3)
- [x] Clean ViewPort (@kbroschke @MariusDoe) (5)
- [x] Write layer tests?
