### ISSUE TITLE
Add ability to draw equilateral triangles

### ISSUE THREAD

**Issue by MariusDoe** [hpi-swa-teaching/SketchMorph2#114]
As a user, I want to draw equilateral triangles with the *Triangle Tool* by holding shift, in order to be precise in my drawings.

**Comment by RogerAK** [comment]
Formula to find the third point of an equilateral triangle, if you have two points.
![image](https://user-images.githubusercontent.com/82659152/169883208-c13f449f-6a53-4b67-b92d-dd2cb980cac5.png)
