### ISSUE TITLE
Zoom-Funktion und Scrollbars (21+)

### ISSUE THREAD

**Issue by DevSchmidtchen** [hpi-swa-teaching/SketchMorph2#37]
Als NutzerIn möchte ich die Anzeigegröße der Leinwand mit Hilfe des Mausrads skalieren und das Blickfeld mit Scrollbars verschieben können, um detaillierter bestimmte Bereiche auf der Leinwand anschauen und bearbeiten zu können.

**Comment by ClFeSc** [comment]
Implemented in #85
