### ISSUE TITLE
Menu item activation doesn't work with undo

### ISSUE THREAD

**Issue by kpostnov** [hpi-swa-teaching/SketchMorph2#49]
When user actions are undone the currently selected tool changes depending on which tool was used last while the corresponding menu item stays unactivated.

**Comment by ClFeSc** [comment]
Can be fixed by implementing #38

**Comment by maximilian-franz** [comment]
https://user-images.githubusercontent.com/80772628/118617820-46d80500-b7c3-11eb-884b-de0066d94cd7.mp4
