### ISSUE TITLE
Add MTF to README

### ISSUE THREAD

**Issue by kpostnov** [hpi-swa-teaching/SketchMorph2#50]
The Morphic Test Framework should be mentioned in the "How to install" - section.

**Comment by maximilian-franz** [comment]
Isn't it sufficient to mention it in the wiki (as it is now)?

**Comment by DevSchmidtchen** [comment]
> Isn't it sufficient to mention it in the wiki (as it is now)?

I think we should at least link to the framework in the README because otherwise all tests will fail after installing the package without changing anything in the code which could result in confusion.
